[package]
name = "iter-diff"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

readme = "README.md"
description = "Differences between iterators"
repository = "https://github.com/ureeves/iter-diff"
homepage = "https://github.com/ureeves/iter-diff"

[dependencies]
